ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ecom/shop/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ShippingAddress
from django import forms

class usercreate(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


Country = (('Bangladesh', 'Bangladesh'),
           ('India', 'India')
           )


Division = (('Dhaka', 'Dhaka'),
             ('Khulna', 'Khulna'),
             ('Rajshahi', 'Rajshahi'),
             ('Rangpur', 'Rangpur'),
             ('Sylhet', 'Sylhet'),
             ('Mymenshing', 'Mymenshing'),
             ('Chattogram', 'Chattogram')
           )

# Divivsion = ('Dhaka', 'Khulna', 'Rajshahi', 'Rangpur', 'Sylhet', 'Mymenshing', 'Chattogram',)

District = (("Bagerhat", "Bagerhat"),
    ("Bandarban", "Bandarban"),
    ("Barguna", "Barguna"),
    ("Barisal", "Barisal"),
    ("Bhola", "Bhola"),
    ("Bogra", "Bogra"),
    ("Brahmanbaria", "Brahmanbaria"),
    ("Chandpur", "Chandpur"),
    ("Chapai Nawabganj", "Chapai Nawabganj"),
    ("Chattogram", "Chattogram"),
    ("Chuadanga", "Chuadanga"),
    ("Cox's Bazar", "Cox's Bazar"),
    ("Cumilla", "Cumilla"),
    ("Dhaka", "Dhaka"),
    ("Dinajpur", "Dinajpur"),
    ("Faridpur", "Faridpur"),
    ("Feni", "Feni"),
    ("Gaibandha", "Gaibandha"),
    ("Gazipur", "Gazipur"),
    ("Gopalganj", "Gopalganj"),
    ("Habiganj", "Habiganj"),
    ("Jamalpur", "Jamalpur"),
    ("Jashore", "Jashore"),
    ("Jhalokathi", "Jhalokathi"),
    ("Jhenaidah", "Jhenaidah"),
    ("Joypurhat", "Joypurhat"),
    ("Khagrachari", "Khagrachari"),
    ("Khulna", "Khulna"),
    ("Kishoreganj", "Kishoreganj"),
    ("Kurigram", "Kurigram"),
    ("Kushtia", "Kushtia"),
    ("Lakshmipur", "Lakshmipur"),
    ("Lalmonirhat", "Lalmonirhat"),
    ("Madaripur", "Madaripur"),
    ("Magura", "Magura"),
    ("Manikganj", "Manikganj"),
    ("Meherpur", "Meherpur"),
    ("Moulvibazar", "Moulvibazar"),
    ("Munshiganj", "Munshiganj"),
    ("Mymensingh", "Mymensingh"),
    ("Naogaon", "Naogaon"),
    ("Narail", "Narail"),
    ("Narayanganj", "Narayanganj"),
    ("Narsingdi", "Narsingdi"),
    ("Natore", "Natore"),
    ("Netrokona", "Netrokona"),
    ("Nilphamari", "Nilphamari"),
    ("Noakhali", "Noakhali"),
    ("Pabna", "Pabna"),
    ("Panchagarh", "Panchagarh"),
    ("Patuakhali", "Patuakhali"),
    ("Pirojpur", "Pirojpur"),
    ("Rajbari", "Rajbari"),
    ("Rajshahi", "Rajshahi"),
    ("Rangamati", "Rangamati"),
    ("Rangpur", "Rangpur"),
    ("Satkhira", "Satkhira"),
    ("Shariatpur", "Shariatpur"),
    ("Sherpur", "Sherpur"),
    ("Sirajganj", "Sirajganj"),
    ("Sunamganj", "Sunamganj"),
    ("Sylhet", "Sylhet"),
    ("Tangail", "Tangail"),
    ("Thakurgaon", "Thakurgaon")
    )

class ShippingForm(forms.ModelForm):
    full_name = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Full Name'}))
    email = forms.CharField(label='', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'Email'}))
    phone_no = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Phone Number'}))
    country = forms.ChoiceField(choices=Country, widget=forms.Select(attrs={'class': 'form-control', 'placeholder':'Country'}))
    division = forms.ChoiceField(choices=Division, widget=forms.Select(attrs={'class': 'form-control', 'placeholder':'Division'}))
    district = forms.ChoiceField(choices=District, widget=forms.Select(attrs={'class': 'form-control', 'placeholder':'District'}))
    address1 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Address1'}))
    address2 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Address2'}), required=False)
    thana = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Thana/Upazilla'}))
    zipcode = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Zipcode'}))

    class Meta:
        model = ShippingAddress
        fields = ['user', 'full_name', 'email', 'phone_no', 'country', 'division', 'district', 'address1', 'address2', 'thana', 'zipcode']

        exclude = ['user',]

class PaymentForm(forms.Form):
    bkash_num = forms.CharField(label='', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Bkash Number'}))
    bkash_txid = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Bkash Transaction ID'}))

ecom/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us - ElectroDokan</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <h2>About ElectroDokan</h2>
        <p>Welcome to ElectroDokan, your premier destination for the latest and greatest in electronics! Whether you're a tech enthusiast, a professional looking for reliable equipment, or someone simply looking to upgrade your home or office, we have everything you need under one roof.</p>

        <h3>Our Mission</h3>
        <p>At ElectroDokan, our mission is to provide our customers with the highest quality electronics at competitive prices, coupled with exceptional customer service. We are dedicated to ensuring that your shopping experience is smooth, enjoyable, and tailored to your specific needs.</p>

        <h3>What We Offer</h3>
        
        <h3>Wide Range of Products</h3>
        <p>We stock a vast array of products to meet all your electronic needs, including:</p>
        <ul>
            <li><strong>Smartphones and Accessories</strong>: Stay connected with the latest models from top brands.</li>
            <li><strong>Laptops and Computers</strong>: From everyday use to high-performance machines, we've got you covered.</li>
            <li><strong>Home Appliances</strong>: Upgrade your home with our range of cutting-edge appliances.</li>
            <li><strong>Audio and Visual Equipment</strong>: Experience superior sound and picture quality with our selection of TVs, speakers, and more.</li>
            <li><strong>Gadgets and Wearables</strong>: Discover the latest in smart technology, from fitness trackers to smartwatches.</li>
            <li><strong>Gaming</strong>: Immerse yourself in the world of gaming with our consoles, games, and accessories.</li>
        </ul>

        <h3>Quality and Reliability</h3>
        <p>We understand that purchasing electronics is an investment. That’s why we only stock products from reputable brands known for their quality and durability. Each item undergoes rigorous testing and quality checks to ensure it meets our high standards.</p>

        <h3>Exceptional Customer Service</h3>
        <p>Our customer service team is always ready to assist you. Whether you need help choosing the right product, have questions about an order, or need after-sales support, we are here to help. Your satisfaction is our top priority.</p>

        <h3>Easy and Secure Shopping</h3>
        <p>Navigating ElectroDokan is easy and intuitive, allowing you to find what you need quickly and efficiently. We offer a variety of secure payment options and ensure that your personal information is protected at all times. Plus, with our fast and reliable shipping, your new electronics will be in your hands in no time.</p>

        <h3>Community and Sustainability</h3>
        <p>ElectroDokan is committed to making a positive impact. We actively participate in community initiatives and prioritize sustainable practices. From eco-friendly packaging to energy-efficient products, we are dedicated to reducing our environmental footprint and promoting sustainability.</p>

        <h2>Join the ElectroDokan Family</h2>
        <p>We invite you to explore our extensive collection of electronics and discover the perfect products for your lifestyle. Follow us on social media for the latest updates, promotions, and tech news. Sign up for our newsletter to receive exclusive offers and stay informed about new arrivals.</p>
        <p>Thank you for choosing ElectroDokan. We look forward to serving you and making your tech dreams a reality!</p>
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ecom/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    
    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap) -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/registration.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock content %}
    
   
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
      </div>
    </footer>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

ecom/templates/billing_info.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <title>Document</title>
    <style>
      @media screen and (min-width: 768px) {
        .card{
          width: 50%;
          margin: 0 auto;
        }
        
        #id_bkash_num{
          margin-bottom: 10px;
        }
      }
      #id_bkash_num{
        margin-bottom: 10px;
      }
      .card-header p {
        display: flex;
        justify-content: center;
        margin-bottom: -2px;
        font-weight: bold;
      }
    </style>
  </head>

  <body>
    {% include 'navbar.html' %}
    <br />
    <div class="container">
      <div class="card">
        <div class="card-header">
          <p>Order Summary</p>
        </div>
        {% for cart in cart %}
          <div class="card-body">
            <div>
              <b>{{ cart.product.title }}</b><br />
              <small>Price: <b>৳{{ cart.product.price }}</b></small><br />
              <small>Quantity: <b>{{ cart.quantity }}</b></small>
            </div>
          </div>
          <hr />
        {% endfor %}
        <h5 class="m-3">Total: ৳{{ total }}</h5><br />
        <div>
          <a href="{% url 'cart' %}"><button class="btn btn-md btn-outline-secondary m-3">Update Cart</button></a>
        </div>
      </div><br /><br /><br />

      <div class="card">
        <div class="card-header">
          <div class="card-header">
            <p>Shipping Information</p>
          </div>
        </div>
        <div class="card-body mb-10">
          <b>Full Name:</b> {{ form.full_name }}<br><br>
          <b>Email:</b> {{ form.email }}<br><br>
          <b>Country:</b> {{ form.country }}<br><br>
          <b>Division:</b> {{ form.division }}<br><br>
          <b>District:</b> {{ form.district }}<br><br>
          <b>Address1:</b> {{ form.address1 }}<br><br>
          <b>Address2:</b> {{ form.address2 }}<br><br>
          <b>Thana/Upazilla:</b> {{ form.thana }}<br><br>
          <b>Zipcode:</b> {{ form.zipcode }}<br>
          <br>
          <a href="{% url 'place_order' %}"><button class="btn btn-outline-secondary">Update Info</button></a>
          
        </div>
      </div><br /><br /><br />
      <div class="card">
        <div class="card-header">
          <div class="card-header">
            <p>Payment</p>
          </div>
        </div>
        <div class="card-body mb-10">
          <form action="{% url 'process_order' %}" method="POST">
            {% csrf_token %}
            {{payment.as_p}}

            <button type="submit" class="btn btn-primary">Pay and Confirm Order Now</button>
          </form>
        </div>
      </div>
      <br/><br /><br />
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

ecom/templates/emptycart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <style>
        .img {
            display: flex;
            justify-content: center;
        }
        .txt{
            display: flex;
            justify-content: center;          
        }
    </style>
</head>

<body>
    {% include "navbar.html" %}

    <div class="img">
        <img src="{% static 'images/empty.png' %}" alt="">

    </div>
    <div class="txt">
        <h3>Your cart is empty now!</h3>
    </div><br>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

ecom/templates/footer.html
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; ElectroDokan 2024</p>
  </div>
</footer>

ecom/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />

    <style>
        #carouselExampleIndicators{
            height: 500px;
            width: 1000px;
            margin: 0 auto;
            margin-top: 25px;
            background: #000;
            margin-bottom: 25px;
            
        }
        .carousel-inner img{
          width: 600px;
          height:500px;
        }
        a{
          text-decoration: none;
          color: #000;
        }
        
    </style>
</head>
<body>
    {% include 'navbar.html' %}

    <div class="container text-center">
      <div class="row">
        <div class="col-sm-2">
          <table class="table" border="2">
            <thead>
              <tr>
                <th scope="col">Category</th>
              </tr>
            </thead>
            <tbody>
              {% comment %} {% for product in product %}
              <tr>
                <th scope="row">{{product.category}}</th>
              </tr>
              {% endfor %}  {% endcomment %}
              <tr>
                <td><a href="{% url 'fan' %}">Fan</a></td>
              </tr>
              <tr>
                <td><a href="{% url 'powerbank' %}">Power Bank</a></td>
              </tr>
              <tr>
                <td><a href="{% url 'smartwatch' %}">Smartwatch</a></td>
              </tr>
              
              
            </tbody>
          </table>
        </div>
        <div class="col-sm-10">
          <div id="carouselExampleIndicators" class="carousel slide">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <a href="#"><img src="{% static 'images/Baseus.Adaman.2000mAh.BDSHOP.jpg.1_nHHmsKr.jpg' %}" class="d-block w-100" alt="..."></a>
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/Haylou-watch-2-pro-Silver.webp' %}" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="{% static 'images/WGP-Mini-UPS-5-12-12.jpg' %}" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        
      </div>


      <hr>
      
      <section class="py-5">
        <h3>Smartwatch</h3>
        <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for sw in sw %}
              <div class="col mb-5">
                <div class="card h-100">
                  
                  <!-- Product image -->
                  <a href="{% url 'productdetail' sw.id %}"><img class="card-img-top" src="{{ sw.image.url }}" alt="..." /></a><hr />
                  <!-- Product details -->
                  <div class="card-body p-4">
                    <div class="text-center">
                      <!-- Product name -->
                      <a href="{% url 'productdetail' sw.id %}" style="text-decoration: none;"><h5 class="fw-bolder" style="color: black; ">{{ sw.title }}</h5></a>
                      <!-- Product price -->
                      ৳{{ sw.price }}
                    </div>
                  </div>
                  <!-- Product actions -->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center">
                      <a class="btn btn-outline-dark mt-auto" href="{% url 'productdetail' sw.id %}">Product Details</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>


        <hr>

        <h3>Power bank</h3>
        <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for pb in pb %}
              <div class="col mb-5">
                
                <div class="card h-100">
                  
                  <!-- Product image -->
                  <a href="{% url 'productdetail' pb.id %}"><img class="card-img-top" src="{{ pb.image.url }}" alt="..." /></a><hr />
                  <!-- Product details -->
                  <div class="card-body p-4">
                    <div class="text-center">
                      <!-- Product name -->
                      <a href="{% url 'productdetail' pb.id %}" style="text-decoration: none;"><h5 class="fw-bolder" style="color: black; ">{{ pb.title }}</h5></a>
                      <!-- Product price -->
                      ৳{{ pb.price }}
                    </div>
                  </div>
                  <!-- Product actions -->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center">
                      <a class="btn btn-outline-dark mt-auto" href="{% url 'productdetail' pb.id %}">Product Details</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <hr>

        <h3>Fan</h3>
        <div class="container px-4 px-lg-5 mt-5">
          <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for fan in fan %}
              <div class="col mb-5">
                
                <div class="card h-100">
                  
                  <!-- Product image -->
                  <a href="{% url 'productdetail' fan.id %}"><img class="card-img-top" src="{{ fan.image.url }}" alt="..." /></a><hr />
                  <!-- Product details -->
                  <div class="card-body p-4">
                    <div class="text-center">
                      <!-- Product name -->
                      <a href="{% url 'productdetail' fan.id %}" style="text-decoration: none;"><h5 class="fw-bolder" style="color: black; ">{{ fan.title }}</h5></a>
                      <!-- Product price -->
                      ৳{{ fan.price }}
                    </div>
                  </div>
                  <!-- Product actions -->
                  <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center">
                      <a class="btn btn-outline-dark mt-auto" href="{% url 'productdetail' fan.id %}">Product Details</a>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <hr>
      </section>

     

    </div>



    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ecom/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
      <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
    </div>
  </div>
</header>
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      {% for product in products %}
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image -->
            <a href="{% url 'productdetail' product.id %}"><img class="card-img-top" src="{{ product.image.url }}" alt="..." /></a><hr />
            <!-- Product details -->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name -->
                <a href="{% url 'productdetail' product.id %}" style="text-decoration: none;"><h5 class="fw-bolder" style="color: black; ">{{ product.title }}</h5></a>
                <!-- Product price -->
                ৳{{ product.price }}
              </div>
            </div>
            <!-- Product actions -->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <a class="btn btn-outline-dark mt-auto" href="{% url 'productdetail' product.id %}">Product Details</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

ecom/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form action="{% url 'login' %}" method="POST" class="form shadow p-3 mb-5 bg-body-tertiary rounded">
          {% csrf_token %}
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Username</label>
            <input type="text" class="form-control" placeholder="Enter Username" id="exampleInputEmail1" aria-describedby="emailHelp" name="username" />
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Enter Password" name="password" />
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock %}

ecom/templates/powerbank.html
{% extends 'base.html' %}

{% block content %}
<!-- Header -->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
      <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
    </div>
  </div>
</header>
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      {% for product in powerbank %}
        <div class="col mb-5">
          <div class="card h-100">
            <!-- Product image -->
            <a href="{% url 'productdetail' product.id %}"><img class="card-img-top" src="{{ product.image.url }}" alt="..." /></a><hr />
            <!-- Product details -->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name -->
                <a href="{% url 'productdetail' product.id %}" style="text-decoration: none;"><h5 class="fw-bolder" style="color: black; ">{{ product.title }}</h5></a>
                <!-- Product price -->
                ৳{{ product.price }}
              </div>
            </div>
            <!-- Product actions -->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center">
                <a class="btn btn-outline-dark mt-auto" href="{% url 'productdetail' product.id %}">Product Details</a>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}